Update seabios.yml

diff --git a/.github/workflows/seabios.yml b/.github/workflows/seabios.yml
--- a/.github/workflows/seabios.yml
+++ b/.github/workflows/seabios.yml
@@ -30,10 +30,10 @@ jobs:
         AVAIL_SEABIOS_V="$(curl -u ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} -s https://api.github.com/repos/ich777/mos-seabios-firmware/releases/latest | jq -r '.tag_name')"
 
         # Check if one of the versions is empty
-        if [[ -z "${SEABIOS_V}" || -z "${AVAIL_SEABIOS_V}" ]]; then
-          echo "Can't get versions"
-          exit 1
-        fi
+        #if [[ -z "${SEABIOS_V}" || -z "${AVAIL_SEABIOS_V}" ]]; then
+        #  echo "Can't get versions"
+        #  exit 1
+        #fi
 
         # Check versions
         if [ "${SEABIOS_V}" == "${AVAIL_SEABIOS_V}" ]; then
@@ -67,6 +67,7 @@ jobs:
 
         cd $BUILDDIR
         chmod -R 755 $PACKAGEDIR
+        chown -R root:root $PACKAGEDIR
         dpkg-deb --build seabios_package mos-seabios-firmware_${SEABIOS_V##*-}_all.deb
         md5sum $BUILDDIR/mos-seabios-firmware_${SEABIOS_V##*-}_all.deb | awk '{print $1}' > $BUILDDIR/mos-seabios-firmware_${SEABIOS_V##*-}_all.deb.md5
 
